### ISSUE TITLE
Please update react-router-dom to latest version 6.6.1

### ISSUE THREAD

**Issue by webdevyriy** [JesusTheHun/storybook-addon-react-router-v6#16]
The latest update added a lot of important functionality.

**Comment by JesusTheHun** [comment]
Can you be specific about the issues you are facing?

**Comment by redbmk** [comment]
Just speculating, but I would assume he's referring to the loader/action/etc features introduced in 6.4

https://github.com/remix-run/react-router/releases/tag/react-router%406.4.0

**Comment by JesusTheHun** [comment]
@redbmk probably yes. But since the title of the issue refers to a peer dependency, I have to ask...

**Comment by JesusTheHun** [comment]
@webdevyriy @redbmk new version available, your feedback is greatly appreciated, please check #21
