### ISSUE TITLE
"No routes matched location" warning when defining reactRouter parameter in a story and triggering a navigation using useNavigate hook

### ISSUE THREAD

**Issue by majoncas-ue** [JesusTheHun/storybook-addon-react-router-v6#17]
Hello!

I have a problem when I'm defining "reactRouter" parameter in my story and I call  a navigation from that component afterwards. I get navigated to an empty page with "No routes matched location" warning. This doesn't happen if don't define "reactRouter" parameter in my story, it stays on the current page and I see proper action in the Storybook tab "Navigate to: {url: "/promotions/21", path: "/promotions/21", routeParams: Object, searchParams: Object, hash: ""…}". This is probably due to the fact that by defining  the router decorator, it only instantiates the current defined route. Is there any workaround?

**Comment by JesusTheHun** [comment]
Hi, I need the code to better understand and reproduce your issue.
What is the current behavior and what is the expected behavior?
