### ISSUE TITLE
Is there a possibility to support Storybook 7 (beta) ?

### ISSUE THREAD

**Issue by bastiengrignon** [JesusTheHun/storybook-addon-react-router-v6#18]
It would be nice to be able to use your addon with Storybook 7. 

Would you be able to do it or you're going to wait until Storybook 7 will release a stable version ?

**Comment by JesusTheHun** [comment]
Hello, to be honest I don't have much time until at least mid-march, and there is already some work to do in order to support data router.
I don't know what needs to be done to support storybook v7 and don't have time to investigate. If you have some insight and/or can make a PR I'm more than willing take a look and merge it.

**Comment by bastiengrignon** [comment]
Ok thanks for the quick response, I completly understand, no problem.
I'll look into it if I have a bit of time too :wink:

**Comment by douglashellowell** [comment]
just bumping some package versions seems to not be causing any obvious issues for me - i'll continue to look into it too 🕵️

```
 @storybook/addon-essentials  ^6.4.0  →  ^7.0.0-beta.45
 @storybook/react             ^6.4.0  →  ^7.0.0-beta.45
 react-router                 ^6.3.0  →          ^6.8.1
 react-router-dom             ^6.3.0  →          ^6.8.1
 ```

**Comment by pellea** [comment]
It's working with the v7. I have those following versions:
```
    "storybook": "^7.0.0-rc.6"
    "storybook-addon-react-router-v6": "^0.3.4"
```

One issue that I have, but not sure if related to Storybook v7 or if it was already there in v6: I cannot update props automatically using the UI if `withRouter` is set in the decorators.

**Comment by JesusTheHun** [comment]
I've started to take a look into v7. Indeed the addon is not impacted directly.
I will still create a new version for SB7 in order to move away from now deprecated APIs, but also in order to harvest the new typescript support !

**Comment by ldm-acn** [comment]
I found a problem with a peer dependency on @storybook/components@"^6.4.0":

I get this conflict:
```
@storybook/components@"^6.4.0" from storybook-addon-react-router-v6@0.3.5
@storybook/components@"^7.0.0" from storybook-react-i18next@2.0.1
```

**Comment by JesusTheHun** [comment]
I'll publish the new version next Thursday

**Comment by bastiengrignon** [comment]
@JesusTheHun I tried but I got an issue on a story with a NavLink component with the following error : `Error: useLocation() may be used only in the context of a <Router> component`

**Comment by JesusTheHun** [comment]
@bastiengrignon can you share your story ? This is very likely an issue with your story

**Comment by JesusTheHun** [comment]
Maybe you should ask on SO ? I don't mind helping but this place is for issues you have identified with the add-on.

**Comment by JesusTheHun** [comment]
Support for Storybook 7 has been added with version `1.0.0`
