### ISSUE TITLE
MemoryRouter doesn't support new features of react-router (from 6.4)

### ISSUE THREAD

**Issue by hugofelp** [JesusTheHun/storybook-addon-react-router-v6#19]
React router has introduced new features and hooks from version 6.4 that require a data router - https://reactrouter.com/en/main/routers/picking-a-router

The addon uses the older `MemoryRouter` implementation, which fails with any new feature from react router:

![image](https://user-images.githubusercontent.com/73772/214158571-b1b8b556-39cc-4c29-84c8-30a083ff91d1.png)

**Comment by JesusTheHun** [comment]
@hugofelp new version available, your feedback is greatly appreciated, please check #21
