### ISSUE TITLE
Typescript typings not setup ?

### ISSUE THREAD

**Issue by VasilyShelkov** [JesusTheHun/storybook-addon-react-router-v6#22]
Hi great work on the library. Is there something I'm missing here ? or is there a type definition file missing or the path in the package.json incorrectly set ? I'm having typescript issues with the package (at version 0.3.0 but couldn't get it to work with 0.2.2 either)

<img width="1319" alt="Screenshot 2023-03-14 at 13 53 40" src="https://user-images.githubusercontent.com/7474810/225023355-3b91e773-d50b-49bf-9cf1-1fdafa1c07fa.png">

**Comment by JesusTheHun** [comment]
Hello, version `0.2.2` is a mistake, it's exactly the same as `0.3.0`. Can you try with `0.2.1`?
What is your initial issue? You can't install the package in a typescript project?

**Comment by BenjaminHoch-GoTo** [comment]
I guess he has the same issue i have after I tried to upgrade to 0.3.0:
my IDE (VSC) complains about missing declaration file:
Could not find a declaration file for module 'storybook-addon-react-router-v6'. '/Users/<user>/<pathToProject>/node_modules/storybook-addon-react-router-v6/dist/cjs/index.js' implicitly has an 'any' type.

**Comment by JesusTheHun** [comment]
Thanks for raising the issue. This has been fixed with version `0.3.1`
