### ISSUE TITLE
Support for multi-level route tree

### ISSUE THREAD

**Issue by afn** [JesusTheHun/storybook-addon-react-router-v6#25]
Is it possible to construct a route tree more than one level deep?

If I understand correctly, `withRouter` constructs a router with a single `<Route>`, and although it's possible to define descendant routes by setting `routePath` to a path ending with `*` and rendering a `<Routes>` within the component, there's no way to have `withRouter` construct a multi-level tree.

As a result, `useMatches` will always return a single match. This means that breadcrumbs implemented by iterating over the matches (as suggested in https://reactrouter.com/en/main/hooks/use-matches) cannot be tested.

As an example, suppose we want to test the `Breadcrumbs` component defined on https://reactrouter.com/en/main/hooks/use-matches, and we want the route tree to look like:

```jsx
<Route path="teams" handle={{ crumb: () => "Teams" }}>
  <Route path=":teamId" handle={{ crumb: () => "AwesomeCorp" }}>
    <Route path="users" handle={{ crumb: () => "Users" }}>
      <Route path=":userId" handle={{ crumb: () => "John Doe" }} element={<Breadcrumbs/>}/>
      </Route>
    </Route>
  </Route>
</Route>
```

Is there a way to accomplish this with `withRouter`?

**Comment by JesusTheHun** [comment]
@afn I was thinking about this yesterday and I was thinking about adding a `matches` property so you can directly define the result of `useMatches`. Would it be a satisfying solution for you ?

**Comment by afn** [comment]
That would certainly work!

**Comment by JesusTheHun** [comment]
I've taken a deeper look, and it's hard to implement as is, because my hackaround `useMatches` actually affects the internals of `react-router` itself.
I am currently testing the use of a helper component that would create the hierarchy of nested routes for you, instead of using dark magic to mimic it.
