### ISSUE TITLE
support for storybook 7?

### ISSUE THREAD

**Issue by ggilley** [JesusTheHun/storybook-addon-react-router-v6#27]
```
$ npm install --save-dev storybook-addon-react-router-v6

npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: ffl@0.1.0
npm ERR! Found: @storybook/addons@7.0.7
npm ERR! node_modules/@storybook/addons
npm ERR!   @storybook/addons@"7.0.7" from @storybook/builder-webpack5@7.0.7
npm ERR!   node_modules/@storybook/builder-webpack5
npm ERR!     @storybook/builder-webpack5@"7.0.7" from @storybook/react-webpack5@7.0.7
npm ERR!     node_modules/@storybook/react-webpack5
npm ERR!       dev @storybook/react-webpack5@"^7.0.7" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! dev storybook-addon-react-router-v6@"*" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: @storybook/addons@6.5.16
npm ERR! node_modules/@storybook/addons
npm ERR!   peer @storybook/addons@"^6.4.0" from storybook-addon-react-router-v6@0.3.5
npm ERR!   node_modules/storybook-addon-react-router-v6
npm ERR!     dev storybook-addon-react-router-v6@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

**Comment by JesusTheHun** [comment]
Hi, the new version should have come already but I got sick... Probably next week!

**Comment by vitalikkabai** [comment]
@JesusTheHun Can we expect an update this week?

**Comment by JesusTheHun** [comment]
@vitalikkabai yes sir ! Working on it right now :)

**Comment by JesusTheHun** [comment]
@ggilley @vitalikkabai Hi, can you try the canary version ?

`npm I -D storybook-addon-react-router-v6@1.3.6--canary.ffa6de3.0`
`yarn add -D storybook-addon-react-router-v6@1.3.6--canary.ffa6de3.0`

**Comment by JesusTheHun** [comment]
@vitalikkabai If we face any issue in the next few days I'll make a new canary version. Otherwise I will make a new stable release with the exact same code. 
It will become the next major and stable version: `1.0.0`.

**Comment by vitalikkabai** [comment]
@JesusTheHun Hello, how are you doing with the development of your addon? If it's possible, could you please let me know if there are any plans for an update in the near future? This addon is important to me, so I'm very interested in your progress and future plans. Thank you!

**Comment by h1karxii** [comment]
I also ran into the same problem, but so far it seems to be working without any issues with the canary version.

**Comment by m2mathew** [comment]
@JesusTheHun On the [releases page](https://github.com/JesusTheHun/storybook-addon-react-router-v6/releases/tag/v1.0.0), the wording seems to indicate that v1.0.0 of this package does not support Storybook v7. I had to come to this issue for clarity. I kindly suggest updating the release note wording.

Thanks for working on this helpful plugin!

**Comment by JesusTheHun** [comment]
@m2mathew Thanks for the message, I've updated the release to fix my mistake 👌
