### ISSUE TITLE
Support for stable @storybook package versions

### ISSUE THREAD

**Issue by bartelemi** [JesusTheHun/storybook-addon-react-router-v6#31]
Peer dependencies are too strict and currently do not allow using stable version of @storybook packages.

```
npm ERR! Found: storybook-addon-react-router-v6@0.3.5
npm ERR! node_modules/storybook-addon-react-router-v6
npm ERR!   dev storybook-addon-react-router-v6@"1.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! dev storybook-addon-react-router-v6@"1.0.0" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: @storybook/theming@7.0.10
npm ERR! node_modules/@storybook/theming
npm ERR!   peer @storybook/theming@"^7.0.0-rc.3" from storybook-addon-react-router-v6@1.0.0
npm ERR!   node_modules/storybook-addon-react-router-v6
npm ERR!     dev storybook-addon-react-router-v6@"1.0.0" from the root project
```

**Comment by JesusTheHun** [comment]
Can you share what version you use ? `@storybook/*` and the addon.

**Comment by bartelemi** [comment]
Apologies for raising this issue, turns out it was a problem with my local node_modules/ directory which somehow got corrupted. `npm` was assuming that there are some incompatible deps and started throwing errors.

However, I think it's better to rely on stable versions of libraries (non release-candidates), so in my opinion the peer dependencies of your package would benefit from being updated.

Having said that, feel free to close this issue as it is actually resolved.

**Comment by Neurrone** [comment]
I'm facing the same issue. Peer dependency resolution is breaking since this package specifies the rc version of various storybook packages.

**Comment by pinetree** [comment]
Yes, facing the same.

I.e.
```
npm ERR! Could not resolve dependency:
npm ERR! peer @storybook/components@"^7.0.0-rc.3" from storybook-addon-react-router-v6@1.0.0
npm ERR! node_modules/storybook-addon-react-router-v6
npm ERR!   dev storybook-addon-react-router-v6@"^1.0.0" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: @storybook/components@7.0.12
npm ERR! node_modules/@storybook/components
npm ERR!   peer @storybook/components@"^7.0.0-rc.3" from storybook-addon-react-router-v6@1.0.0
npm ERR!   node_modules/storybook-addon-react-router-v6
npm ERR!     dev storybook-addon-react-router-v6@"^1.0.0" from the root project
```

**Comment by noveogroup-amorgunov** [comment]
Same problem :(

**Comment by JesusTheHun** [comment]
@Neurrone @pinetree @noveogroup-amorgunov Can you try this version and tell me if it resolves the issue :

```
npm i -D storybook-addon-react-router-v6@1.0.1--canary.a8c156e.0
yarn add -D storybook-addon-react-router-v6@1.0.1--canary.a8c156e.0
```

**Comment by noveogroup-amorgunov** [comment]
<img width="1011" alt="Снимок экрана 2023-05-18 в 19 10 41" src="https://github.com/JesusTheHun/storybook-addon-react-router-v6/assets/21186268/52e32ba2-3638-46fe-be1e-acb8283b7bbf">

@JesusTheHun hello, no changes

**Comment by JesusTheHun** [comment]
Your issue seems to come from `react-inspector`. Can you try version `storybook-addon-react-router-v6@1.0.1--canary.e7845b3.0` ?

**Comment by noveogroup-amorgunov** [comment]
<img width="965" alt="" src="https://github.com/JesusTheHun/storybook-addon-react-router-v6/assets/21186268/d1cc6a24-a6e0-422b-bda7-fd2bd82d71a7">

@JesusTheHun now it's all okay, thanks

**Comment by JesusTheHun** [comment]
@bartelemi @noveogroup-amorgunov @pinetree @Neurrone 
Dependencies have been updated with version 1.0.1

**Comment by EldinZaimovic** [comment]
I am facing same/similar issue with storybook 8
```
Could not resolve dependency:
npm ERR! peer @storybook/blocks@"^8.0.0" from storybook-addon-remix-react-router@3.0.0
npm ERR! node_modules/storybook-addon-remix-react-router
npm ERR!   dev storybook-addon-remix-react-router@"3.0.0" from the root project
```

**Comment by JesusTheHun** [comment]
@EldinZaimovic this is unrelated, `@storybook/blocks` is a peer dependency so you must install it as part of your project.
