### ISSUE TITLE
No way to provide ID

### ISSUE THREAD

**Issue by SpyTec** [JesusTheHun/storybook-addon-react-router-v6#34]
React Router has an ID tag in both `IndexRouteObject` and `NonIndexRouteObject` as you can see here. This provides an easy way of defining routes so allow easier `isActive` classes for elements outside React Router. It would be great to have this added as well

https://github.com/remix-run/react-router/blob/de5e57b1fc7309617208a6dd2ddcbd68fdca48b4/packages/react-router/lib/context.ts#L22-L40

I'm trying to setup Storybook in our project and that seemed like the easiest way to handle links in the tabs here

https://github.com/packit/dashboard/pull/240
![image](https://github.com/JesusTheHun/storybook-addon-react-router-v6/assets/6598829/2704f65f-0dc9-473d-96b9-c7fe47175a34)

**Comment by JesusTheHun** [comment]
Hello 👋 thank you for opening an issue.
That's reasonable and easy to do, I'll add it this week.

**Comment by JesusTheHun** [comment]
@SpyTec support for route id has been added in version `1.0.2`. Can you give it a try and let me know if it fulfil your need ?

**Comment by JesusTheHun** [comment]
I'm closing this, if you have an issue please re-open it.
