### ISSUE TITLE
Support my laziness

### ISSUE THREAD

**Issue by jpink** [JesusTheHun/storybook-addon-react-router-v6#35]
Please support [lazy](https://reactrouter.com/en/main/route/lazy) property in router parameters.

That way I can easily test my `loader`, `action`, `Component`, `ErrorBoundary` parts which are exported (using those names) in my FooPage.jsx file. The testing of actual lazy loading isn't the point. The point is to allow easier and shorter story definition and ensures that parts are exported correctly.

So that way the ultimate minimal story definition would be:
```js
import { withRouter } from 'storybook-addon-react-router-v6'

export default {
  title: 'FooPage',
  decorators: [withRouter],
  parameters: {
    reactRouter: {
      lazy: () => import('./FooPage') // the page exports Component and usually loader, ...
    }
  }
}

export const Foo = {}
```

**Comment by JesusTheHun** [comment]
@jpink I'm closing this as completed. Feel free to re-open if you face any issue.
