### ISSUE TITLE
error TS2307: can't find storybook-channel-mock

### ISSUE THREAD

**Issue by AndreasHerz** [JesusTheHun/storybook-addon-react-router-v6#39]
When I run `tsc` in my application where `storybook-addon-react-router-v6` is installed, I get the following error:

<img width="1113" alt="image" src="https://github.com/JesusTheHun/storybook-addon-react-router-v6/assets/43435739/60c20b89-67d6-4dd0-a498-2b8285a0e139">

storybook version: `7.0.22`
storybook-addon-react-router-v6 version: `1.0.2`

Is there a way I can fix it in my environment or does it need a bugfix?

**Comment by JesusTheHun** [comment]
Can you make a repro ?

**Comment by AndreasHerz** [comment]
I've created a demo repo, but somehow the error didn't appear anymore. 
After some time spending with searching for differences, I could't find a reason for it.
My final solution was to uninstall this package.

I close this issue because there must be something wrong in my environment.

**Comment by JesusTheHun** [comment]
Just to be clear, you simply uninstalled and reinstalled the package, and now it works ? Or you just dropped the package entirely ?
What package manager are you using ?

**Comment by JesusTheHun** [comment]
@AndreasHerz Just to be clear, you simply uninstalled and reinstalled the package, and now it works ? Or you just dropped the package entirely ?
What package manager are you using ?

**Comment by AndreasHerz** [comment]
No, I tried to reconstruct the error in a demo repo. 
I dropped the package from my real repo entirely because I couldn't find a solution & because I couldn't reconstruct the error, I think it has nothing to do with this package. I'm using npm…

**Comment by JesusTheHun** [comment]
I wouldn't go so fast to say it has nothing to do with this package. 
I've noticed runtime errors that sound similar to yours.
v2 will be pre-released soon, I'll ping you when it is so you can give it a try.

**Comment by AndreasHerz** [comment]
Alright, thank you!

**Comment by JesusTheHun** [comment]
Can you try the pre-release ? https://github.com/JesusTheHun/storybook-addon-react-router-v6/releases/tag/v2.0.0-rc.0
