### ISSUE TITLE
Got a warning on Storybook v7.2.0

### ISSUE THREAD

**Issue by aicest** [JesusTheHun/storybook-addon-react-router-v6#40]
Since Storybook [7.2.0](https://github.com/storybookjs/storybook/commit/9f79059ccec5e034e892475d7fc1ae1ad3d5d5dd), the addon render function is called like a component, and the `key` will be consumed by React and not passed to the render function, thus we should not access it inside the addon render function.

<img width="637" alt="image" src="https://github.com/JesusTheHun/storybook-addon-react-router-v6/assets/4016742/c1f9f89f-5afb-4ba4-9d85-8adddc97edb1">

**Comment by JesusTheHun** [comment]
Can you try the v2 ? https://github.com/JesusTheHun/storybook-addon-react-router-v6/releases/tag/v2.0.0-rc.0

**Comment by aicest** [comment]
@JesusTheHun v2 works for me, thanks.
