### ISSUE TITLE
"Encountered two children with the same key" warnings on doc pages

### ISSUE THREAD

**Issue by szymonnowak-st** [JesusTheHun/storybook-addon-react-router-v6#46]
First of all, I really want to thank for the new v2 release, as it seems to have fixed an issue we had where our doc pages that were randomly throwing various errors, like `Error: Minified React error #409`, or ` Maximum call stack size exceeded`.

One tiny issue that we encountered after switching to v2 is that on doc pages, we get the following error in JS console:
```
Warning: Encountered two children with the same key, `storybook/react-router-v6/story-loaded_1`.
Keys should be unique so that components maintain their identity across updates.
Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
```

I don't think it's actually causing any problems, but would be nice to fix.

**Comment by JesusTheHun** [comment]
Hello @szymonnowak-st , thanks for opening an issue.

I'm glad you like the new v2, it took a lot of efforts !

Release `2.0.3` is now out and should fix your warning. Can you give it a go and confirm that it fixes the warning on your side ?
Also if you have 20 seconds to spare, could you answer this poll about the information banner please ? https://github.com/JesusTheHun/storybook-addon-react-router-v6/discussions/47

**Comment by szymonnowak-st** [comment]
I no longer see this error on `2.0.3`. Thanks!

> Also if you have 20 seconds to spare, could you answer this poll about the information banner please ? https://github.com/JesusTheHun/storybook-addon-react-router-v6/discussions/47

Sure! I've just voted and commented :)
