### ISSUE TITLE
Possible Bug on Addon tab output

### ISSUE THREAD

**Issue by Smolations** [JesusTheHun/storybook-addon-react-router-v6#49]
Hello! I have just upgraded from SB6 to SB7 for a personal project and therefore your plugin was also upgraded (2.0.5). I updated the syntax in the stories using your addon. However, it does not appear that the `url` is appearing correctly when `searchParams` are included. The `?` separator is missing:
![image](https://github.com/JesusTheHun/storybook-addon-react-router-v6/assets/952681/fc1d7ab0-5762-49fe-a2b6-651c00304c47)

Luckily, the url with the query param seems to be getting passed to the router as expected because I can see a reference to the value in my component render. I think it's just a typo when that output object is getting constructed. 😅

**Comment by JesusTheHun** [comment]
Hi @Smolations , this is fixed in `v2.0.6`. Can you confirm this on your side ?
