### ISSUE TITLE
Events are not logged in panel with react-router 6.16+

### ISSUE THREAD

**Issue by Ghuntheur** [JesusTheHun/storybook-addon-react-router-v6#54]
# Error

Nothing is printed in react router panel, at story initialization, and during navigation.

# Version
storybook-addon-react-router-v6 => "2.0.7"
react-router-dom => 6.16.0

**Comment by JesusTheHun** [comment]
Can you make a repro ?

**Comment by Ghuntheur** [comment]
Yes, for sure.
You can reproduce it here : [https://codesandbox.io/p/sandbox/router-addon-5dr98n](https://codesandbox.io/p/sandbox/router-addon-5dr98n)

**Comment by JesusTheHun** [comment]
@Ghuntheur I'm happy to confirm that the rule that says "the smaller the issue the bigger the time of investigation" is still true 👌
Can you confirm this is fixed for you with version `2.0.8` ?

**Comment by Ghuntheur** [comment]
I didn't see any change with new version.

**Comment by JesusTheHun** [comment]
This is weird, I used your reproduction repository and it fixed it. You used the same repo ?
Can you remove `node_modules/.cacheˋ and try storybook again ?

**Comment by Ghuntheur** [comment]
Oh yes, it's working now in my reproduction. Thanks, I will update my project now !
