### ISSUE TITLE
Not working with useLocation

### ISSUE THREAD

**Issue by douglasgomes98** [JesusTheHun/storybook-addon-react-router-v6#7]
It's my storybook configuration:
<img width="739" alt="image" src="https://user-images.githubusercontent.com/47008462/186237261-65fff499-56bf-488d-895d-3b6881631db9.png">

It's my story:
![code](https://user-images.githubusercontent.com/47008462/186237569-1edd4326-7bb3-47e5-8ad0-716a7f7810ae.png)

The error; useLocation() may be used only in the context of a <Router> component.

**Comment by JesusTheHun** [comment]
Hi 👋 can you please share all the code involved (with stackblitz for example) ? So I can reproduce the issue and poke around to find the issue.

**Comment by douglasgomes98** [comment]
I managed to get it working, it was project setup where I was using react-router-dom as an external library. thanks!
